module.exports = {
  "description": "Converts the case of text values in a datatable column.",
  "group": "Transformations",
  "subgroup": "Data Tables",
  "input": [
    {
      "name": "data",
      "type": "datatable",
      "description": "The datatable containing the column to be converted.",
      "required": true,
    },
    {
      "name": "column",
      "type": "text",
      "description": "The column to be converted.",
      "required": true,
      "ui": { "column": "data" },
    },
    {
      "name": "case",
      "type": "text",
      "description": "One of the following supported case patterns:\n- `no`\n- `dot`\n- `swap`\n- `path`\n- `upper`\n- `lower`\n- `camel`\n- `snake`\n- `title`\n- `param`\n- `kebab`\n- `hyphen`\n- `header`\n- `pascal`\n- `constant`\n- `sentence`\n- `upperfirst`\n- `lowerfirst`",
      "enum": [
        "no",
        "dot",
        "swap",
        "path",
        "upper",
        "lower",
        "camel",
        "snake",
        "title",
        "param",
        "kebab",
        "hyphen",
        "header",
        "pascal",
        "constant",
        "sentence",
        "upperfirst",
        "lowerfirst",
      ],
      "required": true,
    },
  ],
  "output": [
    {
      "name": "data",
      "type": "datatable",
      "description": "A new datatable with target column added.",
    },
  ],
};
